# Generated by Django 5.1.3 on 2024-11-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_country_post_likes_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
